### ISSUE TITLE
Sometimes extraction of embedded document fails

### ISSUE THREAD

**Issue by bamthomas** [ICIJ/datashare#564]
**Describe the bug**

When extracting embedded document there is a 500 error sent to the front

**To Reproduce**

try to find an embedded document for example an email attachment and try to download it.

**Expected behavior**
Download the embedded document

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser [e.g. chrome, safari] FF
 - Version [e.g. 22] 78.0.2

**Comment by bamthomas** [comment]
maybe related to #179

**Comment by bamthomas** [comment]
there is another cause that may create this kind of bug : it is the overriding of apache commons-codec : 

```
2020-09-16 14:24:53,970 [pool-5-thread-2] ERROR DocumentConsumer - Exception while consuming file: "/home/dev/demo/file.msg".
java.io.IOException: 
        at org.apache.tika.parser.ParsingReader.read(ParsingReader.java:277)
        at java.io.Reader.read(Reader.java:140)
        at org.icij.spewer.Spewer.copy(Spewer.java:121)
        at org.icij.spewer.Spewer.toString(Spewer.java:131)
        at org.icij.datashare.text.indexing.elasticsearch.ElasticsearchSpewer.getDocumentMap(ElasticsearchSpewer.java:132)
        at org.icij.datashare.text.indexing.elasticsearch.ElasticsearchSpewer.prepareRequest(ElasticsearchSpewer.java:87)
        at org.icij.datashare.text.indexing.elasticsearch.ElasticsearchSpewer.writeDocument(ElasticsearchSpewer.java:63)
        at org.icij.spewer.Spewer.write(Spewer.java:56)
        at org.icij.extract.extractor.Extractor.extract(Extractor.java:266)
        at org.icij.extract.extractor.DocumentConsumer.lambda$accept$0(DocumentConsumer.java:126)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoSuchMethodError: org.apache.commons.codec.binary.Hex.encodeHexString([BZ)Ljava/lang/String;
        at org.apache.poi.hpsf.ClassID.toString(ClassID.java:313)
        at org.apache.tika.parser.microsoft.AbstractPOIFSExtractor.handleEmbeddedOfficeDoc(AbstractPOIFSExtractor.java:184)
        at org.apache.tika.parser.microsoft.AbstractPOIFSExtractor.handleEmbeddedOfficeDoc(AbstractPOIFSExtractor.java:146)
        at org.apache.tika.parser.microsoft.OutlookExtractor.parse(OutlookExtractor.java:271)
        at org.apache.tika.parser.microsoft.OfficeParser.parse(OfficeParser.java:199)
        at org.apache.tika.parser.microsoft.OfficeParser.parse(OfficeParser.java:131)
        at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280)
        at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280)
        at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:143)
        at org.apache.tika.parser.ParserDecorator.parse(ParserDecorator.java:188)
        at org.apache.tika.parser.DigestingParser.parse(DigestingParser.java:84)
        at org.apache.tika.parser.ParsingReader$ParsingTask.run(ParsingReader.java:236)
        ... 1 common frames omitted
```

It happened when migrating tika from 1.22 to 1.24.1
